version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./db/redis:/data
    networks:
      - app

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 13306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./data/sql/entrance.sql:/docker-entrypoint-initdb.d/entrance.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - app

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27027:27017
    volumes:
      - ./db/mongo:/data/db
    networks:
      - app

  navigate-service:
    image: navigate-service:latest
    container_name: navigate-service
    build: ./navigate-service
    ports:
      - 18090:8090
    depends_on:
      - mongo
    networks:
      - app

  task-service:
    image: task-service:latest
    container_name: task-service
    build: ./task-service
    ports:
      - 18080:8080
    depends_on:
      - mysql
      - redis
      - navigate-service
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: task-frontend
    ports:
      - 15137:80
    volumes:
      - ./task-frontend/dist:/app/task/html
      - ./task-frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - task-service
    privileged: true
    networks:
      - app

networks:
  app:
