server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/entrance?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    tomcat:
      max-active: 20
  redis:
    host: redis
    port: 6379
    database: 6
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: status
      logic-delete-value: 1
      logic-not-delete-value: 0

navigate:
  url: "http://navigate-service:8090"
